version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "keycash"
      MYSQL_PASSWORD: "keycash"
      MYSQL_ROOT_PASSWORD: "keycash"
    volumes:
      - db_data:/var/lib/mysql